case_id: case-helm-001-host-network
artifact_type: helm_chart

misconfigurations:
  - id: GT-HELM-001

    category: PodSecurity
    subcategory: HostNetwork
    severity: High

    resource:
      kind: Deployment
      namespace: scanner-benchmark
      name: helm-host-network-demo-app
      container: null

    field_path: spec.template.spec.hostNetwork

    bad_value: true
    expected_secure_value: false