apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-demo
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath-demo
  template:
    metadata:
      labels:
        app: hostpath-demo
    spec:
      automountServiceAccountToken: false

      containers:
        - name: demo-container
          image: nginx:1.25

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

          volumeMounts:
            - name: host-filesystem
              mountPath: /host

      volumes:
        - name: host-filesystem
          hostPath:
            path: /
            type: Directory