apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-ipc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host-ipc-demo
  template:
    metadata:
      labels:
        app: host-ipc-demo
    spec:
      hostIPC: {{ .Values.podSecurity.hostIPC }}
      automountServiceAccountToken: false

      containers:
        - name: demo-container
          image: nginx:1.25
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - ALL