apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-account-token-demo
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-account-token-demo
  template:
    metadata:
      labels:
        app: service-account-token-demo
    spec:
      automountServiceAccountToken: true

      containers:
        - name: demo-container
          image: nginx:1.25

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"